-- Enable pg_trgm extension for trigram similarity
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TABLE IF NOT EXISTS achievement (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
-- Create trigram index for similarity searches
CREATE INDEX IF NOT EXISTS achievement_name_trgm_idx ON achievement USING GIN (name gin_trgm_ops);
INSERT INTO achievement (name)
VALUES ('First Steps'),
    ('Quick Learner'),
    ('Problem Solver'),
    ('Code Master'),
    ('Team Player'),
    ('Bug Hunter'),
    ('Performance Expert'),
    ('Security Champion'),
    ('DevOps Hero'),
    ('Innovation Award'),
    ('Fast Learner'),
    ('Rapid Learner'),
    ('Swift Learner'),
    ('Speed Learner'),
    ('Code Wizard'),
    ('Code Ninja'),
    ('Code Expert'),
    ('Master Coder'),
    ('Problem Finder'),
    ('Solution Finder'),
    ('Issue Solver'),
    ('Bug Finder'),
    ('Bug Catcher'),
    ('Bug Squasher'),
    ('Bug Destroyer'),
    ('Team Leader'),
    ('Team Member'),
    ('Team Champion'),
    ('Performance Guru'),
    ('Performance Master'),
    ('Security Expert'),
    ('Security Master'),
    ('Security Guardian'),
    ('DevOps Master'),
    ('DevOps Champion'),
    ('DevOps Expert'),
    ('Innovation Master'),
    ('Innovation Champion'),
    ('Creative Award'),
    ('Excellence Award'),
    ('Outstanding Achievement in Software Engineering'),
    ('Exceptional Problem Solving and Critical Thinking'),
    ('Advanced Database Optimization and Performance Tuning'),
    ('Distinguished Leadership in Technology Innovation'),
    ('Superior Code Quality and Best Practices Implementation'),
    ('Comprehensive Security Analysis and Vulnerability Assessment'),
    ('Professional Development and Continuous Learning Excellence'),
    ('Collaborative Teamwork and Cross-Functional Communication'),
    ('Innovative Solutions for Complex Technical Challenges'),
    ('Expert Level Debugging and Troubleshooting Skills');
