CREATE TABLE IF NOT EXISTS achievement (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
INSERT INTO achievement (name)
VALUES ('First Steps'),
    ('Quick Learner'),
    ('Problem Solver'),
    ('Code Master'),
    ('Team Player'),
    ('Bug Hunter'),
    ('Performance Expert'),
    ('Security Champion'),
    ('DevOps Hero'),
    ('Innovation Award'),
    ('Fast Learner'),
    ('Rapid Learner'),
    ('Swift Learner'),
    ('Speed Learner'),
    ('Code Wizard'),
    ('Code Ninja'),
    ('Code Expert'),
    ('Master Coder'),
    ('Problem Finder'),
    ('Solution Finder'),
    ('Issue Solver'),
    ('Bug Finder'),
    ('Bug Catcher'),
    ('Bug Squasher'),
    ('Bug Destroyer'),
    ('Team Leader'),
    ('Team Member'),
    ('Team Champion'),
    ('Performance Guru'),
    ('Performance Master'),
    ('Security Expert'),
    ('Security Master'),
    ('Security Guardian'),
    ('DevOps Master'),
    ('DevOps Champion'),
    ('DevOps Expert'),
    ('Innovation Master'),
    ('Innovation Champion'),
    ('Creative Award'),
    ('Excellence Award');